server:
  port: 9999

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
  datasource:
    url: jdbc:mysql://mysql-server:3307/coin_exchange?useSSL=false&serverTimezon=GMT%28
    username: root
    password: huangyimin159??
    driver-class-name: com.mysql.cj.jdbc.Driver
# We choose JWT to store the asymmetric pair of key
#  redis:
#    host: redis-server
#    port: 6380
#    password: huangyimin159??
